### ISSUE TITLE
Unknown interaction

### ISSUE THREAD

**Issue by shirishxyz** [ryzyx/discordjs-button-pagination#11]
Everything works fine... the bot sends the message with buttons but whenever I click next or previous it doesn't goes to the next embed (though it the buttons also don't show that the interaction failed) plus there's an error in the terminal: DiscordAPIError: Unknown interaction 
I don't know what's happening I have installed it by: npm i discordjs-button-pagination@msg

**Comment by ryzyx** [comment]
try uninstalling the package using `npm un discordjs-button-pagination` then use `npm i discordjs-button-pagination@msg`

**Comment by thoughts3rased** [comment]
It sounds like you're trying to use the version for standard legacy message embeds using emotes rather than the one for slash commands (since you say there's no message that the interaction failed, which legacy messages don't support), try reinstalling the library without the `@msg` and try again.
