### ISSUE TITLE
Add Support For Deferred Replies

### ISSUE THREAD

**Issue by thoughts3rased** [ryzyx/discordjs-button-pagination#12]
Not all embed generation can be done within 3 seconds, especially for more complex uses such as leaderboards or anything that touches a database. For these cases, deferred replies should also be supported in order to expand the usefulness of the module.

**Comment by ryzyx** [comment]
Good idea, imma do it asap

**Comment by ryzyx** [comment]
Or if you'd like you can create a pull request for it

**Comment by ryzyx** [comment]
nvm i didnt notice the pull request
