### ISSUE TITLE
Latest Merge Defers Already Deferred Replies

### ISSUE THREAD

**Issue by thoughts3rased** [ryzyx/discordjs-button-pagination#15]
The change that was made to the module earlier still errors out when dealing with an interaction with a deferred reply that's passed through, since embed generation will take place before the function is called, making passing an undeferred interaction unfeasable in situations that need it. `deferUpdate()` might be worth a shot.

**Comment by thoughts3rased** [comment]
Line 26 is the main line of focus here, where `deferReply()` is called

**Comment by ryzyx** [comment]
I havent completely worked on it yet. Its getting late for me imma work on it later

**Comment by ryzyx** [comment]
You could also make another pr if you have a stable working code

**Comment by ryzyx** [comment]
Latest version has been tested and published to npm, you can use `npm i discordjs-button-pagination@interaction` or `npm i discordjs-button-pagination@latest` to get the new version
