### ISSUE TITLE
Exemple code to use in Message

### ISSUE THREAD

**Issue by enrico-marques** [ryzyx/discordjs-button-pagination#20]
hello would it be possible an example code to use with normal messages?

**Comment by ryzyx** [comment]
You can read the [README](https://github.com/ryzyx/discordjs-button-pagination/blob/msg/README.md)

**Comment by enrico-marques** [comment]
Thank you

**Comment by ryzyx** [comment]
Yeah sorry for the late response, I was on vacation :D

**Comment by enrico-marques** [comment]
OK everything is fine.  can you tell me how to create a button collector in an event, I want to make it like a starboard but with buttons

**Comment by ryzyx** [comment]
https://discord.js.org/#/docs/main/stable/class/InteractionCollector

You can refer to this
