### ISSUE TITLE
nah

### ISSUE THREAD

**Issue by n6ck** [ryzyx/discordjs-button-pagination#21]
nah

**Comment by ryzyx** [comment]
Which package are you using also do u want it to be a message or interaction?

**Comment by misery196326** [comment]
> Which package are you using also do u want it to be a message or interaction?

I am using the discordjs-button-pagination@msg and yes I want my paginated embed to show up through a message command not a slash command.

**Comment by ryzyx** [comment]
Exactly, kindly read the [README](https://github.com/ryzyx/discordjs-button-pagination/blob/msg/README.md) for the msg package.

**Comment by ryzyx** [comment]
Pass in message correctly to the function

**Comment by ryzyx** [comment]
I mean exactly what I wrote. You can refer to basic JavaScript to know what I am talking about

**Comment by ryzyx** [comment]
Can you send the error then

**Comment by Raahuna** [comment]
@misery196326 I was getting that error too but i fixed that! Maybe it's too late but i want to help.

```js
  const embed = new Discord.MessageEmbed()
  .setDescription(`Hello`)
  message.channel.send({ embeds: [embed], components: [row] }).then((sentMessage) =>
  ```
  **in Discord JS Guide they showed us select menu handler like this:**
  ```js
  client.on('interactionCreate', async interaction => {
	if (!interaction.isSelectMenu()) return;

	if (interaction.customId === 'select') {
		await interaction.update({ content: 'Something was selected!', components: [] });
	}
});
  ```
  I changed `await interaction.update` to `.edit()` then i realized bot is editing the first message when you use command twice so I add a ID to Selection Menu's custom id now it's working. (I tried to descrip but my english is not so good.)
  
  Here is an template:
  ```js
client.on('messageCreate', message => {
  if(message.content === 'select-test') {
  const row = new Discord.MessageActionRow()
  .addComponents(
  new Discord.MessageSelectMenu()
  .setCustomId(`LoveOrHate_${message.id}`)
  .setPlaceholder('Click Here!')
  .addOptions([
    { label: "I love you.", value: "happy", description: `You will make me happy.`},
    { label: "I hate you", value: "sad", description: `You will make me sad.`},
  ])
)

var messageID = message.id

const embed_sad = new Discord.MessageEmbed()
.setDescription(`Uhm, y-you can't make me cry...🥺`)

const embed_happy = new Discord.MessageEmbed()
.setDescription(`Yeeey!`)
//-----------------------------------------------------------------------------//
const embed = new Discord.MessageEmbed()
.setTitle(`How do you think about me?`)
message.channel.send({ embeds: [embed], components: [row] }).then((sentMessage) =>

client.on('interactionCreate', async interaction => {
if(interaction.customId === `LoveOrHate_${messageID}`) {
  await interaction.deferUpdate();
  if(interaction.values[0] === "happy") {
    sentMessage.edit({ embeds: [embed_happy], components: [row] });
   }
  if(interaction.values[0] === "sad") {
    sentMessage.edit({ embeds: [embed_sad], components: [row] });
  }
}
})
)
}
})
  ```
<img src="https://user-images.githubusercontent.com/80279532/141943647-a05d3d4e-93f1-473c-be81-19ad2228f034.png" width="500">

hope i was able to help!
