### ISSUE TITLE
Yo, I have no idea how to use it, do you guys have a discord server for help or so?

### ISSUE THREAD

**Issue by SkayuX** [ryzyx/discordjs-button-pagination#23]

**Comment by ryzyx** [comment]
You can refer to the [README](https://github.com/ryzyx/discordjs-button-pagination/blob/interaction/README.md).

**Comment by SkayuX** [comment]
That's why i'm trying to get some help, it just doesn't work for me.

**Comment by ryzyx** [comment]
Let me know your issue, or you can add me on discord **Ryzyx# 0244**

**Comment by SkayuX** [comment]
nvm got  It, thx for effort
