### ISSUE TITLE
Suggestion: A feature to only make the message author to react to the buttons. not everyone.

### ISSUE THREAD

**Issue by acqualesce** [ryzyx/discordjs-button-pagination#27]
A feature that could only let message,author.id react to the buttons? and not everyone? this way it could send an ephemeral message like "only message.author.id can use this" or something like that?

**Comment by ryzyx** [comment]
You can fork the repo and make changes accordingly.

**Comment by acqualesce** [comment]
thank you! but how do i make it like that?

**Comment by ryzyx** [comment]
Just add a condition such as `message.author`
