### ISSUE TITLE
Cannot read property 'setFooter' of undefined

### ISSUE THREAD

**Issue by Tejas12972** [ryzyx/discordjs-button-pagination#28]
Hello, using the module and sometimes im receiving "Cannot read property 'setFooter' of undefined at origin   "embeds: [pages[page].setFooter(`Page ${page + 1} / ${pages.length}`)]," at line 36

**Comment by ryzyx** [comment]
Oh yeah u cannot set footer while using this package. Refer to the [README](https://github.com/ryzyx/discordjs-button-pagination/blob/interaction/README.md)
