### ISSUE TITLE
Add option to show page title on buttons

### ISSUE THREAD

**Issue by Tesohh** [ryzyx/discordjs-button-pagination#30]
Of course the title pages would be dynamic and based on the titles of previous and next pages
Kind of like this:
![immagine](https://user-images.githubusercontent.com/45905658/142733779-dd4b25e6-95f0-4e61-a52f-1cefcf604ea5.png)

**Comment by ryzyx** [comment]
That's your personal preference. Kindly fork the repo and make changes as u wish
