### ISSUE TITLE
Button disabling timeout

### ISSUE THREAD

**Issue by Mystic135** [ryzyx/discordjs-button-pagination#31]
How can i set the timeout for the button? I am not sure where it is but after 2 mins of inactivity the buttons get disabled, but i want it get disabled in 20-30 seconds of inactivity. How can i do it?

**Comment by ryzyx** [comment]
Pass time has 20000 or 30000 ( pass time in milliseconds) . Refer to [README](https://github.com/ryzyx/discordjs-button-pagination/blob/interaction/README.md)

**Comment by Mystic135** [comment]
> Pass time has 20000 or 30000 ( pass time in milliseconds) . Refer to [README](https://github.com/ryzyx/discordjs-button-pagination/blob/interaction/README.md)



> Pass time has 20000 or 30000 ( pass time in milliseconds) . Refer to [README](https://github.com/ryzyx/discordjs-button-pagination/blob/interaction/README.md)

Umm, where so where to put the ({timeout: 20000})?
My code for the command- https://srcb.in/JJxwCuITyC

**Comment by ryzyx** [comment]
On line 50 `paginationEmbed(message, pages, buttonList); `, change it to `paginationEmbed(message, pages, buttonList, 20000); `

**Comment by Mystic135** [comment]
> On line 50 `paginationEmbed(message, pages, buttonList); `, change it to `paginationEmbed(message, pages, buttonList, 20000); `

Yes it worked, even after changing the `20000` to `10000`. Thank you

**Comment by ryzyx** [comment]
np, happy to help

**Comment by Mystic135** [comment]
> np, happy to help

umm, right now it has two buttons, but how can i add buttons like this and also if you click on the last button or the very first button and that button is disabled until the next button is clicked and the embed is navigated, like this one- 
https://media.discordapp.net/attachments/894131176900554812/915950350945624114/Screenshot_20211202-185427_Discord-Beta.jpg

**Comment by ryzyx** [comment]
For that you can fork the repository and make changes as u would like them to be. I can only make changes which are feasible to everyone

**Comment by Mystic135** [comment]
> For that you can fork the repository and make changes as u would like them to be. I can only make changes which are feasible to everyone

Ik how to fork repositories but idk how to edit a repository i have forked

**Comment by ryzyx** [comment]
u can go to the file u wanna edit and the pencil icon the the top right of the box, refer to a yt vid if u want

**Comment by Mystic135** [comment]
> u can go to the file u wanna edit and the pencil icon the the top right of the box, refer to a yt vid if u want

oh well, i did edit the code by forking this repository, the index.js file actually, and then after i added the amount of buttons i wanted to it didn work. Later i deleted the repository and removed the buttons and went back to normal but everytime i run the command, it shows the error which showed up when the repository was forked and edited (now the repository is deleted yes, but still its showing the same error) idk what to do, if u need my repl link, feel free to dm/me in discord at 𒈒★ Mystic ★𒈒#8924

**Comment by ryzyx** [comment]
Not sure what is causing the problem here

**Comment by Mystic135** [comment]
> Not sure what is causing the problem here

help me fix this error please
if needed link, dm in discord at Olympus#8924 (username changed) 

https://media.discordapp.net/attachments/908321422189924372/918857591864565800/unknown.jpeg

also this repository has been deleted but still this is happening idk why

**Comment by ryzyx** [comment]
Ah i see the error now, delete ur current replit repo and create a new one by directly forking this current repo. Tell me if it works

**Comment by Mystic135** [comment]
> Ah i see the error now, delete ur current replit repo and create a new one by directly forking this current repo. Tell me if it works

Ok sure, will try that out when i get free time and will tell u. Me really busy nowadays making website so i hardly look at this lol
