### ISSUE TITLE
Some discord.js deprecated functions.

### ISSUE THREAD

**Issue by wolfcoderz** [ryzyx/discordjs-button-pagination#36]
MessageEmbed.setFooter and Message.deleted is deprecated on the latest discord.js
Please check it out, thanks!

**Comment by ryzyx** [comment]
sure np

**Comment by ryzyx** [comment]
> MessageEmbed.setFooter and Message.deleted is deprecated on the latest discord.js Please check it out, thanks!

can u share the link where it says setfooter is deprecated and what to use instead
