### ISSUE TITLE
nod(e:9192) DeprecationWarning: Passing strings for MessageEmbed#setFooter is deprecated. Pass a sole object instead.

### ISSUE THREAD

**Issue by Miho1254** [ryzyx/discordjs-button-pagination#40]
why i got this?

**Comment by ryzyx** [comment]
uh share full code and error

**Comment by Miho1254** [comment]
> uh share full code and error

nah this is from the libary not my code

**Comment by ryzyx** [comment]
okay lemme look into it

**Comment by Breeze-ui** [comment]
I reinstalled the package via npm but still get those warnings

**Comment by ryzyx** [comment]
Try again now
