### ISSUE TITLE
How do i add select menus to the pagination?

### ISSUE THREAD

**Issue by krissedout** [ryzyx/discordjs-button-pagination#8]
Title ^

**Comment by ryzyx** [comment]
You can't, the package is solely for pagination and nothing else. If u want select menus, fork the repo and change the code accordingly. And then install ur forked repo as the package. If u want help with this I'd be glad to help

**Comment by krissedout** [comment]
Okay erm... is it possible to auto create embeds for every 5 items in an array and then automatically create a pagination that way?

**Comment by ryzyx** [comment]
No, not with this package.

**Comment by krissedout** [comment]
Okay.
